version: "3.8"

services:
  portfolio:
    image: guilherme-martins/portfolio:latest

    ports:
      - "3002:3000"

    environment:
      - NODE_ENV=production

    networks:
      - npm_public

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  npm_public:
    external: true
